sonar.projectKey=AnEstuardoBarriosg_NodeGoat
sonar.organization=anestuardobarriosg
sonar.host.url=https://sonarcloud.io

sonar.projectName=NodeGoat
sonar.projectVersion=1.0

sonar.sources=.
sonar.sourceEncoding=UTF-8
